### ISSUE TITLE
Sensible interfaces: remove `interface` suffix from names

### ISSUE THREAD

**Issue by dnaber-de** [dnaber-de/Requisite#1]
http://verraes.net/2013/09/sensible-interfaces/

**Comment by bueltge** [comment]
Ich verstehe den Artikel, aber sorgt der Suffix nicht für Übersicht? 
Da fehlt mir der Alltag damit, in der ide sicher kein Theme beim Lesen im Repo schwieriger.

**Comment by dnaber-de** [comment]
> beim Lesen im Repo schwieriger

Ich unterteile das mal in zwei Situationen:

 <ul>
<li> _Lesen des Codes_
z.B. einer Methodensignatur:

``` php
public function addRule( Rule $rule ) {
    // do something with rule
}
```

In dieser Situation ist es für das Verständnis des Codes unerheblich, ob es sich beim Type-hint `Rule` um ein Interface oder eine Implementierung handelt. Das Interface von `$rule` sollte man ohnehin kennen oder zumindest aus der Verwendung heraus ableiten können.
</li>
<li> _Lesen der Dateinamen im Verzeichnis_
Hier kann es tatsächlich unübersichtlich werden. Das ist dann aber in der Regel ein Zeichen von zu unspezifischen Namen oder zu unspezifischer Struktur (z.B. dutzende Klassen/Interfaces in »Model«). Gerade bei solchen relativ kleinen, spezifischen Dingen wie einem Autoloader, bietet sich aber an, Wert auf die Semantik und präzise Bezeichnungen zu legen.
</li>
</ul>

**Comment by bueltge** [comment]
Ja. Selbst bei Dateinamen passt es hier, man erkennt sie durch die Einfachheit, keine Spezifika. Insofern gehe ich mit, mir fehlt nur die Übung diese Form von Code mehr zu lesen.
